### ISSUE TITLE
Dockerfile does not build

### ISSUE THREAD

**Issue by brassel** [jspenmar/slowtv_monodepth#1]
Hello there,

thank you for this interesting project!
I am not sure what the role of your Dockerfile is in the project.
The requirements are huge and it does not build from `nvcr.io/nvidia/nvhpc:23.5-devel-cuda_multi-ubuntu22.04` which I guess is the source of the base image.
After some hours of building, conda will report conflicts among the requirements.

Does the file work for you?

Thank you and kind regards

**Comment by jspenmar** [comment]
Hey, 

Thanks for your interest! The base for the image should be `nvidia/cuda:11.7.0-cudnn8-devel-ubuntu20.04` and it has the same requirements as the miniconda environment. 
I primarily use the miniconda version, but decided to include docker instructions in case other people prefer using that. I tried building the docker image myself and had no problems. Are you still seeing this issue? 

Kind regards,
Jaime

**Comment by brassel** [comment]
Hi,

thanks for answering!
That is strange that it works without problems for you. I have literally let it run for a whole afternoon and evening, about six hours. And then it failed. A colleague of mine had the same problem. But then we succeeded in created a much lighter Dockerfile with which it works fine.
Are you interested in presenting it here? 
We could create a pull request.

And I would have another question if I may. 
But to keep things orderly, I will ask it in a separate thread.

Thank you for this interesting work!

**Comment by jspenmar** [comment]
Hmm strange that it doesn't work. Have you had issues just building the Miniconda env? 
Either way, I'd be happy to see the pull request for the lighter Docker file! Thank you :) 

And feel free to open a new issue for your other question. 

Kind regards,
Jaime

**Comment by brassel** [comment]
Sorry, it took a bit longer than expected. But now the pull request is completed.

> Have you had issues just building the Miniconda env?

Yes, and I am sure that it is because of the many entries in the environment.yaml (348 if I remember correctly).
I have now added a `requirements.txt` with 6 dependencies. 
But there will still be a lot of sub dependencies for sure.
