### ISSUE TITLE
all the 'train_disp' entries in Wandb are the same color

### ISSUE THREAD

**Issue by z-x-j** [jspenmar/slowtv_monodepth#5]
When I'm training my own dataset, all the 'train_disp' entries in Wandb are the same color. Have the authors encountered this before?"

**Comment by jspenmar** [comment]
Hi, 

It would help if you could provide additional details, such as what dataset you're training on, how long, and if you've made any changes to the code. The disparities are expected to be a uniform value when they are initialised, but should get better as the model trains. 

Kind regards,
Jaime
