### ISSUE TITLE
Typo in get_mask in evaluator.py

### ISSUE THREAD

**Issue by xapaxca** [jspenmar/slowtv_monodepth#7]
Hi Jaime,

Great job done!

I believe I've identified a typo in [evaluator.py](https://github.com/jspenmar/slowtv_monodepth/blob/main/src/core/evaluator.py). It appears that the Eigen crop is applying the NYU mask, and vice versa, the NYU crop is applying the Eigen mask.

```
    def get_mask(self, target: ty.A) -> ty.A:
        """Helper to mask ground-truth depth based on the selected range and Eigen crop."""
        mask = target > self.min
        if self.max: mask &= target < self.max
        if self.use_eigen_crop: mask &= self._get_nyud_mask(target.shape)
        if self.use_nyud_crop: mask &= self._get_eigen_mask(target.shape)
        return mask
```

Thank you!

**Comment by jspenmar** [comment]
Fixed now! Thanks for pointing it out
